import './globals.css';

import Footer from "@/components/layout/footer";

export const metadata = {
  title: 'Mypage',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
